import {executionPanel,routineTracker,completionToggle} from './ui/tracking.js';
import {actionBadge} from './domain/tracking.js';
import {el,button,row,field} from './ui/dom.js';
import {createMap,sorted,actions,setPillar,setAction,deletePillar,deleteAction,togglePriority,copyMap,LIMITS} from './domain/map.js';
import {blocks,blockCells,SLOTS} from './domain/layout.js';
import {loadLibrary,saveLibrary,conflictInfo} from './storage/localStorage.js';
import {importPdf,importMessages} from './import/validateImport.js';
import {generatePdf,FILENAME,actionDetail} from './pdf/generatePdf.js';
import {now,displayDate} from './utils/dates.js';
let library,storageBlocked=false,storageProblem='';
try{library=loadLibrary();}catch{library={maps:[],activeMapId:null};storageBlocked=true;storageProblem='Не удалось прочитать сохранённые карты. Исходная библиотека не перезаписана. Сохраните текущую работу в PDF; проверьте доступ к хранилищу браузера.';}
let map=library.maps.find(m=>m.id===library.activeMapId)||null,focus=null,editor=null,timer,saved=true,importError='',conflict=null,exporting=false,noticeTimer;
const main=document.querySelector('#main');const fileInput=document.querySelector('#pdf-file');
const privacy='Карта хранится на вашем устройстве. При сохранении её данные записываются внутрь PDF, чтобы вы могли позже продолжить работу.';
function notify(message){const node=document.querySelector('#notice');node.textContent=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>node.textContent='',7000);}
function save(){clearTimeout(timer);try{if(storageBlocked)throw new Error();saveLibrary(library);saved=true;}catch{saved=false;storageProblem='Не удалось сохранить на устройстве. Возможно, память заполнена или хранилище недоступно. Сохраните карту в PDF, чтобы не потерять работу.';}updateStatus();}
function changed(){syncProjection();if(map)map.updatedAt=now();saved=false;updateStatus();clearTimeout(timer);timer=setTimeout(save,400);}
function syncProjection(){if(!map)return;document.querySelectorAll('[data-cell-kind]').forEach(node=>{const kind=node.dataset.cellKind,pos=Number(node.dataset.position),p=map.pillars.find(p=>p.id===node.dataset.pillarId);const entity=kind==='goal'?map.goal:kind==='pillar'?map.pillars.find(p=>p.position===pos):p?.actions.find(a=>a.position===pos);paintCell(node,kind,entity);node.classList.toggle('empty',!entity);});const next=document.querySelector('[data-next-pillar]');if(next)next.disabled=!map.pillars.find(p=>p.id===map.activePillarId)?.actions.length;document.querySelectorAll('[data-map-counts]').forEach(n=>n.textContent=counts(map));}
function paintCell(node,kind,entity){node.replaceChildren(el('span',{class:'cell-text'},entity?.text||(node.tagName==='BUTTON'?'+':'')));if(kind==='action'&&entity){node.append(el('span',{class:`action-kind kind-${entity.type}`},actionBadge(entity)));node.classList.toggle('action-complete',entity.type==='deadline'&&!!entity.completedOn);}}
function editTrackedAction(a){focus=a.pillar.id;editor={kind:'action',position:a.position,pillarId:a.pillar.id};render();document.querySelector('#editor')?.scrollIntoView({block:'center'});}
function updateStatus(){const status=document.querySelector('#save-status');if(status)status.textContent=storageProblem?'Не сохранено на устройстве':saved?'Сохранено':'Сохраняем…';const problem=document.querySelector('#storage-problem');if(problem){problem.textContent=storageProblem;problem.hidden=!storageProblem;}}
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
function go(state){map.onboardingState=state;editor=null;focus=null;changed();render();}
function openMap(m){save();map=m;library.activeMapId=m.id;focus=m.onboardingState==='ACTIONS'?m.activePillarId:null;editor=null;save();render();}
function home(){save();map=null;focus=null;editor=null;library.activeMapId=null;save();render();}
function create(){const m=createMap();library.maps.push(m);openMap(m);}
function pickPdf(){fileInput.value='';fileInput.click();}
document.querySelector('#home').onclick=home;
function counts(m){return `${m.pillars.length} направлений · ${actions(m).length} действий`;}
function title(kicker,heading,body){return el('div',{class:'intro'},el('p',{class:'eyebrow'},kicker),el('h1',{},heading),body?el('p',{class:'lead'},body):null);}
function shell(...content){main.replaceChildren(el('p',{id:'storage-problem',class:'warning',hidden:!storageProblem},storageProblem),...content.filter(Boolean));}
function render(){try{if(!map){startScreen();return;}const toolbar=el('div',{class:'workspace-bar'},button('← Ваши карты',home,'plain'),el('span',{id:'save-status',role:'status'},''),map.onboardingState!=='GOAL'?button('Сохранить карту',()=>exportMap(map),'plain'):null,map.goal.text&&map.onboardingState!=='COMPLETE'?button('Перейти к карте',()=>go('COMPLETE'),'plain'):null);
 shell(toolbar);const state=map.onboardingState;
 if(state==='GOAL'||state==='START')goalSetup();else if(state==='CONTEXT')contextSetup();else if(state==='PILLARS')pillarSetup();else if(state==='MAP_REVEAL')reveal();else if(state==='ACTIONS')actionSetup();else if(state==='REVIEW')review();else if(state==='PRIORITIES')priorities();else workspace();
 syncProjection();updateStatus();main.focus({preventScroll:true});
 }catch(e){console.error(e);shell(title('Цели','Не получилось открыть этот экран','Ваши сохранённые данные остаются на устройстве.'),row(button('Вернуться к картам',home),map?.goal.text?button('Сохранить карту',()=>exportMap(map)):null));}}
function startScreen(){shell(el('div',{class:'start-layout'},el('section',{},title('ИНСТРУМЕНТ / 01','Цели','Разложите одну большую цель на то, от чего она зависит, а затем — на конкретные действия.'),el('p',{class:'subtitle'},'Интерактивная карта Open Window 64 по методу Харады'),row(button('Создать карту',create,'primary'),button('Восстановить карту из PDF',pickPdf)),el('p',{class:'privacy'},privacy),el('p',{class:'privacy'},'PDF обрабатывается прямо в браузере и никуда не отправляется.')),diagram()),importPanel(),el('section',{class:'library'},el('div',{class:'section-heading'},el('h2',{},'Ваши карты'),el('span',{},library.maps.length?`${library.maps.length} на этом устройстве`:'Здесь появятся ваши карты')), ...[...library.maps].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)).map(m=>el('article',{class:'library-card'},el('div',{},el('h3',{},m.goal.text||'Новая карта'),el('p',{class:'muted'},counts(m)),el('p',{class:'small'},'Изменено '+displayDate(m.updatedAt))),row(button('Продолжить',()=>openMap(m),'primary'),button('Сохранить карту',()=>exportMap(m)),button('Удалить',()=>{if(confirm('Удалить эту карту с устройства? Это действие нельзя отменить.')){library.maps=library.maps.filter(x=>x.id!==m.id);save();render();}},'plain'))))));}
function diagram(){return el('div',{class:'start-diagram','aria-hidden':'true'},...Array.from({length:9},(_,i)=>el('div',{class:i===4?'demo-center':'demo-cell'},i===4?'Одна\nцель':i===1?'Направления':i===7?'Действия':'')));}
function importPanel(){if(importError)return el('section',{class:'import-panel',role:'alert'},el('h2',{},'Не получилось восстановить карту'),el('p',{},importError),row(button('Выбрать другой PDF',pickPdf),button('Создать новую карту',()=>{importError='';create();})));
 if(!conflict)return null;const {existing,incoming,newer}=conflictInfo(conflict.existing,conflict.incoming);return el('section',{class:'import-panel'},el('h2',{},'На устройстве уже есть эта карта'),el('p',{},newer==='same'?'Версии имеют одинаковое время изменения.':newer==='device'?'Версия на устройстве изменена позже.':'Версия из PDF изменена позже.'),el('p',{class:'small'},`Устройство: ${new Date(existing.updatedAt).toLocaleString('ru')} · PDF: ${new Date(incoming.updatedAt).toLocaleString('ru')}`),row(button('Открыть версию с устройства',()=>{conflict=null;openMap(existing);}),button('Открыть версию из PDF',()=>{library.maps=library.maps.map(m=>m.id===incoming.id?incoming:m);conflict=null;openMap(incoming);}),button('Сохранить PDF как копию',()=>{const copy=copyMap(incoming);library.maps.push(copy);conflict=null;openMap(copy);})) );}
fileInput.onchange=async()=>{const file=fileInput.files[0];if(!file)return;try{if(file.size>15*1024*1024)throw {code:'too-large'};const incoming=await importPdf(await file.arrayBuffer());incoming.onboardingState='COMPLETE';const existing=library.maps.find(m=>m.id===incoming.id);importError='';if(existing){save();map=null;library.activeMapId=null;conflict={existing,incoming};render();}else{library.maps.push(incoming);openMap(incoming);notify('Карта восстановлена из PDF.');}}catch(e){importError=importMessages[e.code]||importMessages.corrupted;home();}};
function goalSetup(){const next=button('Поместить цель в центр',()=>{if(map.goal.text.trim())go('CONTEXT');},'primary',{disabled:!map.goal.text.trim()});main.append(el('section',{class:'narrow'},title('01 / ОДНА ЦЕЛЬ','Чего вы хотите достичь?','Сформулируйте один конкретный результат. Лучше такой, про который потом можно будет сказать: получилось или нет.'),field('Ваша цель','textarea',map.goal.text,v=>{map.goal.text=v;next.disabled=!v.trim();changed();},LIMITS.goal),row(next)));}
function contextSetup(){const step=map.contextStep||0;main.append(el('section',{class:'narrow'},el('div',{class:'goal-seed'},map.goal.text),title('01 / КОНТЕКСТ · НЕОБЯЗАТЕЛЬНО',step?'Почему вам важна эта цель?':'Когда вы хотите этого достичь?',step?'Не для отчёта. Это понадобится вам, когда цель начнёт конкурировать с другими делами.':null),field(step?'Почему это важно':'Желаемый срок',step?'textarea':'date',step?map.goal.purpose:map.goal.targetDate,v=>{if(step)map.goal.purpose=v;else if(v)map.goal.targetDate=v;else delete map.goal.targetDate;changed();},step?LIMITS.purpose:undefined),row(button('Продолжить',()=>{if(step)go('PILLARS');else{map.contextStep=1;changed();render();}},'primary'),button('Пропустить',()=>{if(step)go('PILLARS');else{map.contextStep=1;changed();render();}},'plain'))));}
function pillarSetup(){const next=button('Продолжить',()=>go('MAP_REVEAL'),'primary',{disabled:!map.pillars.length});const count=el('p',{class:'muted'},'');const update=()=>{count.textContent=`Сейчас заполнено ${map.pillars.length} из 8. Можно продолжить и вернуться к остальным позже.`;next.disabled=!map.pillars.length;};const grid=el('div',{class:'focus-grid setup-grid'});for(let i=0;i<9;i++){if(i===4){grid.append(el('div',{class:'cell goal'},map.goal.text));continue;}const pos=SLOTS.indexOf(i),p=map.pillars.find(p=>p.position===pos);grid.append(el('textarea',{class:'cell input-cell',value:p?.text||'',maxLength:LIMITS.pillar,placeholder:'+',rows:3,'aria-label':`Направление ${pos+1}`,oninput:e=>{const text=e.target.value,existing=map.pillars.find(p=>p.position===pos);if(text.trim())setPillar(map,pos,text);else if(existing&&!existing.actions.length)deletePillar(map,existing.id);changed();update();},onkeydown:e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const fields=[...grid.querySelectorAll('textarea')];const nextField=fields.find(t=>!t.value.trim()&&t!==e.target)||fields[(fields.indexOf(e.target)+1)%fields.length];nextField.focus();}}}));}
 main.append(title('02 / НАПРАВЛЕНИЯ','От чего зависит эта цель?','Назовите до восьми вещей, которые должны сложиться, чтобы цель стала возможной. Это могут быть навыки, ресурсы, привычки, системы, люди, условия или отдельные направления работы.'),el('p',{class:'muted'},'Это пока не список конкретных задач.'),grid,count,row(next));update();}
function overview(){const grid=el('div',{class:'map-grid','aria-label':'Вся карта Open Window 64'});for(const b of blocks(map)){const p=map.pillars.find(p=>p.position===b.position);const cellNodes=b.cells.map(c=>el('span',{class:`mini-cell ${c.kind==='goal'?'goal':c.kind==='pillar'?'pillar':''}`,'data-cell-kind':c.kind,'data-position':c.position,'data-pillar-id':c.pillar?.id},c.entity?.text||''));grid.append(button('',()=>{focus=b.position===null?'center':p?.id||`new:${b.position}`;editor=null;if(p){map.activePillarId=p.id;changed();}render();},`mini-block ${b.position===null?'central-block':''} ${p?.id===map.activePillarId?'active-block':''}`,{'aria-label':b.position===null?'Открыть цель и направления':p?`Открыть направление ${p.position+1}: ${p.text}. ${p.actions.length} из 8 действий`:`Добавить направление ${b.position+1}`}));grid.lastChild.append(...cellNodes);}
 return grid;}
function reveal(){main.append(title('03 / КАРТА РАСКРЫВАЕТСЯ','Теперь превратим каждое направление в действия','Не нужно придумывать 64 пункта сразу. Будем разбирать карту по одному блоку.'),mapView(),row(button('Начать',()=>{map.activePillarId=sorted(map.pillars)[0]?.id;go('ACTIONS');},'primary')));}
function navigatePillar(delta){const ps=sorted(map.pillars);const index=ps.findIndex(p=>p.id===map.activePillarId);const next=ps[index+delta];if(next){map.activePillarId=next.id;focus=next.id;editor=null;changed();render();}else if(delta>0){map.reviewStep=0;go('REVIEW');}}
function actionSetup(){const p=map.pillars.find(p=>p.id===map.activePillarId)||sorted(map.pillars)[0];if(!p){go('PILLARS');return;}map.activePillarId=p.id;main.append(title('03 / ДЕЙСТВИЯ',`Что конкретно поможет вам с «${p.text}»?`,'Добавьте до восьми вещей, которые можно сделать, создать, изменить или регулярно выполнять.'),el('p',{class:'muted'},`${p.text} — ${p.actions.length}/8 · ${map.pillars.filter(p=>p.actions.length).length} из ${map.pillars.length} направлений разобраны`));if(focus==='overview'){main.append(overview());}else{main.append(focus&&focus!==p.id?mapView():focusBlock(p));}main.append(row(button('← Предыдущее',()=>navigatePillar(-1),'',{disabled:sorted(map.pillars)[0].id===p.id}),button('Вся карта',()=>{focus='overview';editor=null;render();}),button('Следующее направление',()=>navigatePillar(1),'primary',{'data-next-pillar':'true',disabled:!p.actions.length}),button('Пропустить',()=>navigatePillar(1),'plain')));}
function focusBlock(p){const root=el('section',{class:'focus-layout'}),area=el('div',{});if(map.onboardingState!=='ACTIONS')area.append(row(button('← Вся карта',()=>{focus=null;editor=null;render();},'plain')));const grid=el('div',{class:'focus-grid'});const center=!p;for(const c of blockCells(map,center?null:p.position)){const label=c.entity?.text||'+';grid.append(button(label,()=>{editor={kind:c.kind,position:c.position,pillarId:p?.id};render();document.querySelector('#editor textarea')?.focus();},`cell ${c.kind==='goal'?'goal':c.kind==='pillar'?'pillar':''} ${!c.entity?'empty':''}`,{'data-cell-kind':c.kind,'data-position':c.position,'data-pillar-id':p?.id,'aria-label':c.kind==='goal'?'Изменить цель':`${c.kind==='pillar'?'Направление':'Действие'} ${(c.position??p?.position)+1}: ${c.entity?.text||'Добавить'}`}));}area.append(grid);if(p&&map.onboardingState!=='ACTIONS'){const ps=sorted(map.pillars),i=ps.findIndex(x=>x.id===p.id);area.append(row(button('← Предыдущее',()=>{focus=ps[i-1].id;map.activePillarId=focus;editor=null;changed();render();},'',{disabled:i===0}),button('Следующее →',()=>{focus=ps[i+1].id;map.activePillarId=focus;editor=null;changed();render();},'',{disabled:i===ps.length-1})));}root.append(area);if(editor)root.append(cellEditor());else root.append(el('aside',{class:'focus-note'},el('p',{class:'eyebrow'},center?'ЦЕЛЬ И НАПРАВЛЕНИЯ':'ОДНО НАПРАВЛЕНИЕ'),el('p',{},'Выберите ячейку, чтобы добавить или изменить её содержание.'),el('p',{class:'small'},'Пустые ячейки можно оставить на потом.')));return root;}
function cellEditor(){const e=editor,p=map.pillars.find(p=>p.id===e.pillarId);let entity=e.kind==='goal'?map.goal:e.kind==='pillar'?map.pillars.find(p=>p.position===e.position):p?.actions.find(a=>a.position===e.position);const panel=el('section',{id:'editor',class:'editor','aria-label':'Редактор ячейки'});const name=e.kind==='goal'?'Цель':e.kind==='pillar'?'Направление':'Действие';const warning=el('p',{class:'small',role:'status'});const textarea=field(name,'textarea',entity?.text,v=>{if(!v.trim()){warning.textContent='Напишите текст или используйте «Удалить». Предыдущая формулировка пока сохранена.';return;}warning.textContent='';if(e.kind==='goal')map.goal.text=v;else if(e.kind==='pillar')entity=setPillar(map,e.position,v);else entity=setAction(map,e.pillarId,e.position,v);changed();},LIMITS[e.kind]);panel.append(el('h2',{},name),textarea,warning);
 if(e.kind==='goal'){panel.append(field('Желаемый срок','date',map.goal.targetDate,v=>{if(v)map.goal.targetDate=v;else delete map.goal.targetDate;changed();}),field('Почему это важно','textarea',map.goal.purpose,v=>{map.goal.purpose=v;changed();},LIMITS.purpose));}
 if(e.kind==='action'){
 const details=el('div',{});const select=el('select',{'aria-label':'Что это?',onchange:ev=>{if(!entity){notify('Сначала напишите действие.');ev.target.value='idea';return;}entity.type=ev.target.value;changed();showDetails();}},...Object.entries({idea:'Пока идея',deadline:'Разовое действие',routine:'Регулярное действие'}).map(([v,t])=>el('option',{value:v},t)));select.value=entity?.type||'idea';panel.append(el('label',{class:'field'},el('span',{},'Что это?'),select),details);
 function showDetails(){details.replaceChildren();if(entity?.type==='deadline'){details.append(completionToggle(map,entity.id,changed));details.append(field('Сделать до · необязательно','date',entity.deadline,v=>{if(v)entity.deadline=v;else delete entity.deadline;changed();}));}if(entity?.type==='routine'){const custom=el('div',{});const freq=el('select',{'aria-label':'Как часто?',onchange:ev=>{entity.frequency={type:ev.target.value};changed();showDetails();}},...Object.entries({daily:'Каждый день',several_times_week:'Несколько раз в неделю',weekly:'Раз в неделю',custom:'Свой вариант'}).map(([v,t])=>el('option',{value:v},t)));if(!entity.frequency){entity.frequency={type:'daily'};changed();}freq.value=entity.frequency.type;function showCustom(){custom.replaceChildren();if(entity.frequency.type==='custom')custom.append(field('Свой вариант','text',entity.frequency.value,v=>{entity.frequency.value=v;changed();},LIMITS.frequency));}details.append(el('label',{class:'field'},el('span',{},'Как часто?'),freq),custom);showCustom();details.append(routineTracker(map,entity.id,{onChange:changed,onError:notify,compact:true}));}}showDetails();}
 panel.append(row(button('Готово',()=>{editor=null;render();},'primary'),e.kind!=='goal'?button('Удалить',()=>{if(e.kind==='pillar'){const target=map.pillars.find(p=>p.position===e.position);if(target?.actions.length&&!confirm('Вместе с направлением будут удалены связанные с ним действия. Удалить направление?'))return;if(target)deletePillar(map,target.id);}else if(entity)deleteAction(map,e.pillarId,entity.id);editor=null;changed();render();},'plain'):null));return panel;}
function mapView(){if(!focus)return overview();if(focus==='center')return focusBlock(null);if(focus.startsWith('new:')){const position=Number(focus.split(':')[1]);focus='center';editor={kind:'pillar',position};return focusBlock(null);}const p=map.pillars.find(p=>p.id===focus);if(!p){focus=null;return overview();}return focusBlock(p);}
function review(){const step=map.reviewStep||0;const questions=['Здесь есть что-то, что на самом деле не помогает вашей цели?','Чего не хватает?','Какие пункты уже стали конкретными действиями, а какие пока остаются идеями?'];main.append(title(`04 / РЕВИЗИЯ · ${step+1} ИЗ 3`,'Посмотрите на карту целиком',questions[step]),el('p',{class:'muted'},'Откройте любой блок, чтобы изменить карту. Пустые ячейки — место для новых мыслей.'),mapView(),row(step?button('← Назад',()=>{map.reviewStep=step-1;changed();render();}):null,button(step===2?'К действиям':'Дальше',()=>{if(step===2)go('PRIORITIES');else{map.reviewStep=step+1;focus=null;editor=null;changed();render();}},'primary')));}
function priorities(){main.append(title('05 / БЛИЖАЙШИЕ ДЕЙСТВИЯ','С чего вы действительно начнёте?','Выберите из карты до 10 действий, которые хотите вынести из размышлений в реальную жизнь.'),el('p',{class:'muted',role:'status'},`Выбрано ${map.priorityActionIds.length} из 10. Можно начать с одного или вернуться к выбору позже.`));if(!actions(map).length)main.append(el('p',{},'В карте пока нет действий. Добавьте их в любом направлении.'));for(const p of sorted(map.pillars)){if(!p.actions.length)continue;main.append(el('fieldset',{class:'priority-group'},el('legend',{},p.text),...sorted(p.actions).map(a=>el('label',{class:'priority-option'},el('input',{type:'checkbox','data-priority-id':a.id,checked:map.priorityActionIds.includes(a.id),onchange:()=>{try{togglePriority(map,a.id);changed();render();document.querySelector(`[data-priority-id="${CSS.escape(a.id)}"]`)?.focus();}catch(e){notify(e.message);render();document.querySelector(`[data-priority-id="${CSS.escape(a.id)}"]`)?.focus();}}}),el('span',{},a.text,el('small',{},actionDetail(a)))))));}main.append(priorityList(),row(button('Готово',()=>go('COMPLETE'),'primary')));}
function priorityList(){const selected=actions(map).filter(a=>map.priorityActionIds.includes(a.id));return el('section',{class:'priorities'},el('div',{class:'section-heading'},el('h2',{},'Ближайшие действия'),map.onboardingState==='COMPLETE'?button('Изменить выбор',()=>go('PRIORITIES'),'plain'):null),!selected.length?el('p',{class:'muted'},'Пока не выбраны. Вы можете вернуться к этому позже.'):null,el('div',{class:'priority-columns'},...Object.entries({deadline:'Сделать',routine:'Повторять',idea:'Пока определить'}).filter(([type])=>selected.some(a=>a.type===type)).map(([type,title])=>el('div',{},el('h3',{},title),el('ul',{},...selected.filter(a=>a.type===type).map(a=>el('li',{},button(a.text,()=>{focus=a.pillar.id;editor={kind:'action',position:a.position,pillarId:a.pillar.id};map.onboardingState='COMPLETE';render();document.querySelector('#editor')?.scrollIntoView({block:'center'});},'text-button'),el('small',{},a.pillar.text+' · '+actionDetail(a)))))))));}
function workspace(){main.append(title('ВАША КАРТА',map.goal.text),row(map.goal.targetDate?el('p',{class:'muted'},'Срок: '+displayDate(map.goal.targetDate)):null,button('Изменить цель и контекст',()=>{focus='center';editor={kind:'goal',position:null};render();},'plain')),map.goal.purpose?el('p',{class:'purpose'},map.goal.purpose):document.createTextNode(''),!focus?executionPanel(map,{onChange:changed,onError:notify,onEdit:editTrackedAction,onChoose:()=>go('PRIORITIES'),onReview:()=>{map.reviewStep=0;go('REVIEW');}}):document.createTextNode(''),el('div',{class:'section-heading'},el('h2',{},'Карта'),el('span',{class:'small','data-map-counts':'true'},counts(map))),mapView(),row(button('Добавить / изменить направления',()=>{focus='center';editor=null;render();}),button('Пройти ревизию',()=>{map.reviewStep=0;go('REVIEW');})),el('section',{class:'save-section'},row(button('Сохранить карту',()=>exportMap(map),'primary'),button('Восстановить карту из PDF',pickPdf)),el('p',{class:'privacy'},privacy)));}
async function exportMap(m){if(exporting)return;exporting=true;notify('Готовим PDF…');const snapshot=structuredClone(m);try{const bytes=await generatePdf(snapshot),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),dialog=document.querySelector('#save-dialog');const link=el('a',{href:url,download:FILENAME,class:'button primary'},'Скачать PDF');const file=new File([blob],FILENAME,{type:'application/pdf'});dialog.replaceChildren(el('h2',{id:'save-title'},'Сохранить карту'),el('p',{},'PDF содержит карту, трекеры выбранного месяца, ваши отметки и все данные для продолжения работы.'),row(link,navigator.canShare?.({files:[file]})?button('Поделиться / в «Файлы»',async()=>{try{await navigator.share({files:[file],title:'Цели'});}catch(e){if(e.name!=='AbortError')notify('Не получилось открыть меню. Используйте «Скачать PDF».');}}):null),el('p',{class:'privacy'},privacy),button('Закрыть',()=>dialog.close(),'plain'));dialog.onclose=()=>{setTimeout(()=>URL.revokeObjectURL(url),60000);};dialog.showModal();notify('PDF готов.');}catch(e){console.error(e);notify('Не удалось создать PDF. '+(e.message||'Попробуйте ещё раз.'));}finally{exporting=false;}}
document.addEventListener('focusin',e=>{if(e.target.matches('textarea,input,select'))setTimeout(()=>e.target.scrollIntoView({block:'nearest',behavior:'smooth'}),250);});
window.addEventListener('error',()=>notify('Произошла ошибка. Сохранённая библиотека остаётся на устройстве.'));
render();
if('serviceWorker' in navigator){let controlled=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(controlled){save();location.reload();}controlled=true;});navigator.serviceWorker.register('./sw.js').catch(()=>{});}
